CREATE TABLE `Crypto` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `symbol` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `Conversion` ADD CONSTRAINT `Conversion_crypto_fkey` FOREIGN KEY (`crypto`) REFERENCES `Crypto`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `Favorite` ADD CONSTRAINT `Favorite_crypto_fkey` FOREIGN KEY (`crypto`) REFERENCES `Crypto`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
