name: Add PRs to Project 19

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to GitHub Project 19
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Murilo-Carazato/projects/19
          github-token: ${{ secrets.GITHUB_TOKEN }}
